apps/list/urls.py
from django.conf.urls import url
from . import views

app_name='list'
urlpatterns=[
	url(r'^lindex$', views.index, name='lindex'),
	url(r'^makeItem$', views.makeItem, name='makeItem'),
	url(r'^createItem$', views.createItem, name='createItem'),
]

apps/login/urls.py
from django.conf.urls import url
from . import views

app_name= 'login'
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^register$', views.register, name='register'),
	url(r'^login$', views.login, name='login'),
	url(r'^logout$', views.logout, name='logout'),
	url(r'^success$', views.success, name='success'),

]

wishList/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.login.urls', namespace='login')),
    url(r'^', include('apps.list.urls', namespace='list')),
]

apps/list/models.py
from __future__ import unicode_literals

from django.db import models
from ..login.models import User

class ItemManager(models.Manager):
	def makeItem(self, postData):
		status={'valid':True, 'errors':[]}
		if not postData['name'] or len(postData['name']) < 3:
			status['valid']=False
			status['errors'].append('Invalid Item. Check your porduct')

		item = Item.objects.filter(name=postData['name'])

		if status['valid'] is False:
			try:
				status['errors'].append('Item was not created. Try agian')
			except:
				item = Item.objects.create(name=postData['name'], owner=User.objects.get(id=postData['owner']))
				item.save()
		return status

	def add_to_list(self, item_id, user_id):
		status={'valid':True, 'errors':[]}
		try:
			item = Item.objects.get(id=item_id)
			item.wanted.add(user_id)
		except IntegrityError as e:
			status['valid']=False
			status['errors'].append(e.message)

		return status

	
class Item(models.Model):
	name = models.CharField(max_length=255)
	owner = models.ForeignKey('login.User', related_name='owner')
	wanted = models.ManyToManyField('login.User', related_name='wanted')
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

	objects = ItemManager()

	def __str__(self):
		return self.name

apps/login/models.py
from __future__ import unicode_literals
from django.db import models, IntegrityError
import bcrypt
import re

class UserManager(models.Manager):
	def registerVal(self, postData):
		results = {'status':True, 'errors':[], 'user':None}
		if not postData['name'] or len(postData['name']) < 3:
			results['status']=False
			results['errors'].append('enter a valid name')
		if not postData['username'] or len(postData['username']) < 3:
			results['status']=False
			results['errors'].append('enter a valid username')
		if not postData['password'] or len(postData['password']) < 8:
			results['status']=False
			results['errors'].append('please enter a valid password')
		if postData['password'] != postData['passvalid']:
			results['status'] = False
			results['errors'].append('Passwords do not match')

		user = User.objects.filter(username=postData['username'])

		if results['status']:
			try:
				user = User.objects.create(name=postData['name'], username=postData['username'], password=(bcrypt.hashpw(postData['password'].encode(), bcrypt.gensalt())))
				user.save()
				results['user']=user
			except IntegrityError as e:
				results['status']=False
				if 'UNIQUE constraint'in e.message:
					results['errors'].append('username already in system')
				else:
					results['errors'].append(e.message)
		return results

	def loginVal(self, postData):
		results = {'status':True, 'errors':[], 'user':None}
		try:
			user = User.objects.get(username=postData['username'])
			if user.password == bcrypt.hashpw(postData['password'].encode(), user.password.encode()):
				pass
			else:
				raise Exception()
		except Exception as e:
			results['status']=False
			results['errors'].append('incorrect Username or password')

		if results['status']:
			results['user'] = user
		return results

class User(models.Model):
	name = models.CharField(max_length=255)
	username= models.CharField(max_length=255)
	password = models.CharField(max_length=255)

	objects = UserManager()

apps/list/views.py
from __future__ import unicode_literals
from django.shortcuts import render, HttpResponse, redirect
from django.core.urlresolvers import reverse
from django.contrib import messages
from .models import User, Item


def index(request):
	checkID(request)
	user = User.objects.get(id=request.session.get('id'))
	items = Item.objects.all()
	context={
		'items': items,
		'user': user,

	}
	return render(request, 'list/index.html', context)

def makeItem(request):
	checkID(request)
	return render(request, 'list/createItem.html')

def createItem(request):
	checkID(request)
	status = Item.objects.makeItem(request.POST)
	if not status['valid']:
		for error in status['errors']:
			messages.error(request, error)
			return redirect('list:makeItem')
	else:
		messages.success(request, 'Item has been created')

	return redirect(reverse('list:lindex'))

def addToList(request, item_id, user_id):
	checkID(request)
	status = Item.objects.add_to_list(item_id, user_id)
	if not status['valid']:
		for error in status['errors']:
			messages.error(request, error)
	else:
		messages.success(request, 'Item added to Your Wish List')
	return redirect('list:lindex')

def checkID(request):
	 if not request.session.get('id'):
	 	messages.error(request, 'Access Denied. Log in first.')
	 	return redirect('login:index')
# Create your views here.

    

apps/login/views.py
from __future__ import unicode_literals
from django.shortcuts import render, HttpResponse, redirect
from django.contrib import messages
from django.core.urlresolvers import reverse
from .models import User

def index(request):
	# if request.session.get('id'):
	# 	return redirect('katBook:userPage')

	return render(request, 'login/index.html')


def register(request):
	
	results = User.objects.registerVal(request.POST)
	

	if not results['status']:
		for error in results['errors']:
			messages.error(request, error)
			
	else:
		messages.success(request, 'User created, please log in.')
	return redirect(reverse('login:index'))

def login(request):
	results = User.objects.loginVal(request.POST)
	if not results['status']:
		for error in results['errors']:
			messages.error(request, error)
	else:
		request.session['id'] = results['user'].id
		return redirect(reverse('list:lindex'))
	return redirect(reverse('login:index'))

def logout(request):
	request.session.clear()
	return redirect(reverse('login:index'))

def success(request):
	user = User.objects.get(id=request.session['id'])
	
	return redirect(reverse('list:lindex'))

apps/list/templates/list/createItem.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Create Item</title>
    </head>
    <body>
    <h1>Create a New Wish List Item</h1>
    {% if messages %}
    <ul>
    	{%  for message in messages %}
    	<li>{{ message }}</li>
    	{% endfor %}
    </ul>
    {% endif %}
      <form action="{% url 'list:createItem' %}" method="post">
      {% csrf_token %}
       	Item/Product: <input type="text" name="name" placeholder="Enter Item Name" />
       	<input type="hidden" name="owner" value="{{request.session.id}}"/>
       	<input type="submit" name="submit" value="Add"/>
       </form> 
    </body>
</html>

apps/list/templates/list/index.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Untitled</title>
    </head>
    <body>
      <h1>Welcome {{user.name}}</h1>
      <p><a href="{% url 'login:logout' %}">logout</a></p>
      {% if messages %}
		<ul>
			{% for message in messages %}
			<li>{{ message }}</li>
			{% endfor %}
		</ul>
		{% endif %}
      <h3>Your Wish List:</h3>
    	<table class="bordered">
    		<thead>
    			<tr>
    				<th name="item">Item</th>
    				<th name="user">Added By</th>
    				<th name="price">Date Added</th>
    				<th name="action">Action</th>
    			</tr>
    		</thead>
    	   <p>{{items.name}}</p>
    		<tbody>
    			
    			{% for items in user.items %}
                <tr>
    				 
    				<td>{{item.name}}</td>
    				<td>{{item.user}}</td>
    				<td>{{item.created}}</td>
    				<td><a href="{% url 'list:delete' %}">Delete from Database</a><a href="">Remove from my List</a></td>
    				
                    </tr>
    			{% endfor %}
    			
    			</tbody>
    	</table>
    	<br>
    	<h3>Other User's Wish List:</h3>
    	<table class="bordered">
    		<thead>
    			<tr>
    				<th name="item">Item</th>
    				<th name="user">Added By</th>
    				<th name="price">Date Added</th>
    				<th name="action">Action</th>
    			</tr>
    		</thead>
    	
    		<tbody>
    			{% for items in user.item %}
                <tr>

    				{% if item.owner.id == user.id %}
    				<td>{{items.name}}</td>
    				<td>{{items.owner}}</td>
    				<td>{{items.created}}</td>
    				<td><a href="{% url 'list:addToList' %}">Add to my WistLost</a></td>
    				{% endif %}
                    </tr>
    			{% endfor %}
    			
    			<tr>
    				
    			</tr>
    		</tbody>
    	</table>
    	<form action="{% url 'list:makeItem' %}" method='post'>
        {% csrf_token %}
    		<input type="submit" name="submit" value="Create Item">
        
    	</form>
    </body>
</html>

apps/login/templates/login/index.html
<!doctype html>
<html>
    <head>
    {% load static %}
        <meta charset="utf-8">
        <title>Wish List</title>
        <link rel="stylesheet" href="{% static 'login/css/index.css' %}">
    </head>
    <body>
      <div id='wrap'>
      <h1>Welcome!</h1>
      {% if messages %}
      	{% for message in messages %}
      	<p>{{ message }}</p>
		    {%endfor%}      	
      {% endif %}
      <h2>Register Here</h2>
      <form action="{% url 'login:register' %}" method="post">
      {% csrf_token %}
       	Name: <input type="text" name="name" placeholder="Enter Your nae" /><br><br>
       	Username: <input type="text" name="username" placeholder="Enter Username" /><br><br>
       	Password: <input type="password" name="password" placeholder="Enter Password" /><br>
        <sub><i>Password should be at least 8 characters</i></sub><br>
       	Confirm Password: <input type="password" name="passvalid" placeholder="Confirm Password" /><br><br>
       	Date Hired: <input type="date" name="doh" placeholder="" /><br>
       	<button type="submit" name="submit" value="register">Register</button>
       </form> 
       <h2>Login Here</h2>
       <form action="{% url 'login:login' %}" method="post">
       {% csrf_token %}
       	Username: <input type="text" name="username" value="" placeholder=""/><br><br>
       	Password: <input type="password" name="password" value="" placeholder=""/><br>
       	<button type="submit" name="submit" value="login">Login</button>
       </form>
       </div>
    </body>
</html>